---
# Hosts file for the majority of roles.
debian_webrole:
  hosts:
  vars:
    # Connection details. Consider encrypting with ansible-vault.
    ansible_user:
    ansible_port:
    ansible_become_password:
    ansible_ssh_private_key_file:
    # Extra logging folder location.
    ansible_custom_log: /var/log/extralogs
    default_inet_interface: enp1s0
    # Package configuration defaults.
    logwatch_custom_detail: 7
    unattendedup_reboot_time: 02:00
    # Unattended-upgrades reboot time (If reboot is required after update).
    # Docker webserver image and image name selection. Tested with chainguardnginx.
    # May want to use 2 different technologies for security purposes.
    webserver_container_name: chainguardnginx
    docker_webserver_image: cgr.dev/chainguard/nginx
    # Currently binds both webserver and docker port to the same port. Todo: Allow binding to separate ports.
    webserver_http_port: 8080
    webproxy_host_address:
    # Docker reverse proxy image and configuration.
    webproxy_container_name: chainguardnginx
    docker_webproxy_image: cgr.dev/chainguard/nginx
    webproxy_http_port: 8080
    webserver_host_address:

debian_openvpn:
  hosts:
  vars:
    # Connection details. Consider encrypting with ansible-vault.
    ansible_user:
    ansible_port:
    ansible_become_password:
    ansible_ssh_private_key_file:
    # Extra logging folder location.
    ansible_custom_log: /var/log/extralogs
    default_inet_interface: enp1s0
    # Package configuration defaults.
    logwatch_custom_detail: 7
    # Unattended-upgrades reboot time (If reboot is required after update).
    unattendedup_reboot_time: 02:00
    # Client name for the OpenVPN/Wireguard roles. Used for both Setup as well as Maintenance roles.
    vpn_client_name:
    vpn_ip_whitelist:
    ansible_openvpn_port:
    ansible_wireguard_port:
